---
- name: prepare instance for build
  hosts: buildinstance
  become: yes
  tasks:

    - name: preinstall python3
      raw: sudo apt-get -y install python python3

    - name: update apt cache
      apt:
        update_cache: yes

    - name: ensure that maven, git, jdk is present
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - maven
          - git
          - default-jdk
          - mc
          - python

    - name: clone boxfuse git repository
      git:
        repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
        dest: ./
        clone: no

    - name: build the project
      shell: mvn boxfuse-sample-java-war-hello/pom.xml package

    - name: fetch war to server
      fetch:
        src: ./boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /tmp/
        flat: yes

- name: run war in deployinstance
  hosts: deployinstance
  become: yes

  tasks:
    - name: ensure tomcat is present
      apt:
        name: tomcat8
        state: present

    - name: ensure tomcat is started
      service:
        name: tomcat8
        state: started

    - name: copy war to prod
      copy:
        src: /tmp/hello-1.0.war
        dest: /var/lib/tomcat8/webapps/